[workspace]
members = ["types", "consumer", "uniffi-bindgen", "core"]
resolver = "3"

[workspace.dependencies]
core = { path = "./core" }
types = { path = "./types" }
consumer = { path = "./consumer" }

uniffi = "0.29.4"
