[package]
name = "consumer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
types.workspace = true
core.workspace = true

uniffi.workspace = true
